services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: booking-sys
    container_name: booking-sys
    ports:
      - "8000:8000"
      - "5173:5173"
    env_file:
      - .env
    command: ["/entrypoint.sh"]
