# Generated by Django 5.1.1 on 2024-09-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
