# Generated by Django 5.1 on 2024-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("reservation_date", models.DateField()),
                ("reservation_slot", models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
