name: Build and deploy container app to Azure Web App - booking-sys

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image to ACR
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/booking-sys:${{ github.sha }} -f Dockerfile .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/booking-sys:${{ github.sha }}
